version: '3.8'

services:
  
  crdb :
    image: cockroachdb/cockroach:v22.1.6
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure
    volumes:
      - "${PWD}/cockroach-data:/cockroach/cockroach-data"